export const DATE_TYPES = Object.freeze({
	EXACT: 'EXACT',
	WEEK: 'SEMAINE',
	QUARTER: 'TRIMESTRE',
})

export const DATE_PATTERNS = Object.freeze({
	EXACT: /^\d{2}\/\d{2}\/\d{4}$/,
	WEEK: /^\d{4}-([1-9]|[1-4][0-9]|5[0-2])$/,
	QUARTER: /^\d{4}-[1-4]$/,
})

export const DATE_ERROR_MESSAGE = Object.freeze({
	EXACT: 'Le format de la date doit être le suivant : JJ/MM/AAAA',
	WEEK: 'Le format de la date doit être le suivant : AAAA-[1-52]',
	QUARTER: 'Le format de la date doit être le suivant : AAAA-[1-4]',
})

export const DATE_TITLES = Object.freeze({
	EXACT: 'Indiquez une date au format JJ/MM/AAAA',
	WEEK: 'Indiquez le numéro de la semaine AAAA-[1-52]',
	QUARTER: 'Indiquez le trimestre AAAA-[1-4]',
})

export const INPUT_TYPES = Object.freeze({
	TEXT: 'text',
	URL: 'url',
	PASSWORD: 'password',
	EMAIL: 'email',
	TEL: 'tel',
	SEARCH: 'search',
})

export const ORDER = Object.freeze({
	ASC: 'ASC',
	DESC: 'DESC',
})

export const STORE = Object.freeze({
	GETTERS: Object.freeze({
		OVERLAY_COMPONENT: 'OVERLAY_COMPONENT',
		PROJECT_GET: 'PROJECT_GET',
		FILES_GET_BY_PROJECT: 'FILES_GET_BY_PROJECT',
		FILES_GET: 'FILES_GET',
		PROJECT_GET_LEFT: 'PROJECT_GET_LEFT',
		PROJECT_GET_RIGHT: 'PROJECT_GET_RIGHT',
	}),
	MUTATIONS: Object.freeze({
		SET_EVENT_SOURCE: 'SET_EVENT_SOURCE',
		CLOSE_EVENT_SOURCE: 'CLOSE_EVENT_SOURCE',
		SET_SENDER: 'SET_SENDER',
		SET_USER_TOKEN: 'SET_USER_TOKEN',
		SET_STATUS: 'SET_STATUS',
		SET_FIELDS: 'SET_FIELDS',
		SET_USER: 'SET_USER',
		SET_USERS: 'SET_USERS',
		SET_ADMIN: 'SET_ADMIN',
		SET_IS_MOBILE: 'SET_IS_MOBILE',
		SET_IS_SCROLL: 'SET_IS_SCROLL',
		PROJECTS_SET_LIST: 'PROJECTS_SET_LIST',
		PROJECTS_ADD: 'PROJECTS_ADD',
		PROJECTS_UPDATE: 'PROJECTS_UPDATE',
		PROJECTS_REMOVE: 'PROJECTS_REMOVE',
		PROJECTS_SET_DATE: 'PROJECTS_SET_DATE',
		PROJECTS_SET_FILTERED: 'PROJECTS_SET_FILTERED',
		PROJECTS_SET_FILTERS: 'PROJECTS_SET_FILTERS',
		PROJECTS_SET_SORTED: 'PROJECTS_SET_SORTED',
		PROJECTS_SET_SEARCH: 'PROJECTS_SET_SEARCH',
		PROJECTS_SET_SEARCHED: 'PROJECTS_SET_SEARCHED',
		PROJECTS_SELECT: 'PROJECTS_SELECT',
		PROJECTS_UNSELECT: 'PROJECTS_UNSELECT',
		PROJECTS_SET_PENDING: 'PROJECTS_SET_PENDING',
		PROJECTS_SET_LEFT: 'PROJECTS_SET_LEFT',
		PROJECTS_SET_RIGHT: 'PROJECTS_SET_RIGHT',
		PROJECTS_SWITCH_VIEW: 'PROJECTS_SWITCH_VIEW',
		HISTORY_ADD: 'HISTORY_ADD',
		HISTORY_UPDATE: 'HISTORY_UPDATE',
		HISTORY_REMOVE: 'HISTORY_REMOVE',
		OVERLAY_SET_VISIBLE: 'OVERLAY_SET_VISIBLE',
		OVERLAY_SET_CONTENT: 'OVERLAY_SET_CONTENT',
		CONFIRM_SET_HEADER: 'CONFIRM_SET_HEADER',
		CONFIRM_SET_TEXT: 'CONFIRM_SET_TEXT',
		CONFIRM_SET_ACTION: 'CONFIRM_SET_ACTION',
		CONFIRM_SET_DETAILS: 'CONFIRM_SET_DETAILS',
		POPUPS_ADD: 'POPUPS_ADD',
		POPUPS_REMOVE: 'POPUPS_REMOVE',
		FILES_SET_LIST: 'FILES_SET_LIST',
		FILES_ADD: 'FILES_ADD',
		FILES_REMOVE: 'FILES_REMOVE',
	}),
	ACTIONS: Object.freeze({
		INIT: 'INIT',
		INIT_EVENT_SOURCE: 'INIT_EVENT_SOURCE',
		FETCH_STATUS: 'FETCH_STATUS',
		FETCH_ADMIN: 'FETCH_ADMIN',
		FETCH_USER: 'FETCH_USER',
		PROJECTS_FETCH_DATE: 'PROJECTS_FETCH_DATE',
		PROJECTS_FETCH: 'PROJECTS_FETCH',
		PROJECTS_POST: 'PROJECTS_POST',
		PROJECTS_PUT: 'PROJECTS_PUT',
		PROJECTS_DELETE: 'PROJECTS_DELETE',
		PROJECTS_FILTER: 'PROJECTS_FILTER',
		PROJECTS_SORT: 'PROJECTS_SORT',
		PROJECTS_SEARCH: 'PROJECTS_SEARCH',
		PROJECTS_TO_LEFT: 'PROJECTS_TO_LEFT',
		PROJECTS_TO_RIGHT: 'PROJECTS_TO_RIGHT',
		HISTORY_POST: 'HISTORY_POST',
		HISTORY_PUT: 'HISTORY_PUT',
		HISTORY_DELETE: 'HISTORY_DELETE',
		OVERLAY_SHOW: 'OVERLAY_SHOW',
		OVERLAY_HIDE: 'OVERLAY_HIDE',
		OVERLAY_SHOW_PROJECT_FORM: 'OVERLAY_SHOW_PROJECT_FORM',
		OVERLAY_SHOW_FILTERS_FORM: 'OVERLAY_SHOW_FILTERS_FORM',
		OVERLAY_SHOW_SORTING_FORM: 'OVERLAY_SHOW_SORTING_FORM',
		OVERLAY_SHOW_FILE_FORM: 'OVERLAY_SHOW_FILE_FORM',
		OVERLAY_SHOW_SIDE_VIEW_SELECTOR: 'OVERLAY_SHOW_SIDE_VIEW_SELECTOR',
		OVERLAY_LOAD: 'OVERLAY_LOAD',
		OVERLAY_UNLOAD: 'OVERLAY_UNLOAD',
		CONFIRM_SHOW: 'CONFIRM_SHOW',
		CONFIRM_HIDE: 'CONFIRM_HIDE',
		FILES_FETCH_ALL: 'FILES_FETCH_ALL',
		FILES_POST: 'FILES_POST',
		FILES_DOWNLOAD: 'FILES_DOWNLOAD',
		FILES_DELETE: 'FILES_DELETE',
	}),
})

export const FILTER_KEYS = Object.freeze({
	TITLE: 'title',
	STATUS: 'status',
	PRIORITY: 'priority',
	APPLICANT: 'applicant',
	SERVICE: 'service',
	USERS: 'users',
	PROGRESSION: 'progression',
	REFERENT_BUSINESS: 'referent_business',
	REFERENT_INFO: 'referent_info',
	DEVELOPERS: 'developers',
	FIELDS: 'fields',
	DATE_RANGE: 'date_range',
})

export const OVERLAY = Object.freeze({
	CONTENT_TYPES: Object.freeze({
		PROJECT_FORM: 'PROJECT_FORM',
		FILTERS_FORM: 'FILTERS_FORM',
		SORTING_FORM: 'SORTING_FORM',
		CONFIRM: 'CONFIRM',
		FILE_FORM: 'FILE_FORM',
		LOADER: 'LOADER',
		SIDE_VIEW_SELECTOR: 'SIDE_VIEW_SELECTOR',
	}),
	ACTIONS: Object.freeze({
		REMOVE_PROJECT: 'REMOVE_PROJECT',
		REMOVE_HISTORY_ITEM: 'REMOVE_HISTORY_ITEM',
		REMOVE_FILE: 'REMOVE_FILE',
	}),
})

export const CUSTOM_EVENTS = Object.freeze({
	UPDATE_VALUE: 'update:value',
})

export const STATUS = Object.freeze({
	WAITING: 'EN ATTENTE',
	PROGRESS: 'EN COURS',
	RECIPE: 'RECETTE',
	PRODUCTION: 'PRODUCTION',
	CANCELLED: 'ANNULE',
})

export const USERS = Object.freeze({
	SUPERADMIN: 'SUPERADMIN',
	GESTION: 'GESTION',
	BACKOFFICE: 'BACKOFFICE',
	DIRECTION: 'DIRECTION',
	DSI: 'DSI',
	COTISATION: 'COTISATION',
	COMMISSIONS: 'COMMISSIONS',
	COMPTABILITE: 'COMPTABILITE',
	COMPLIANCE: 'COMPLIANCE',
	MARKETING: 'MARKETING',
	RH: 'RH',
	PREVOYANCE: 'PREVOYANCE',
	IARD: 'IARD',
})

export const FIELDS = Object.freeze({
	DEVELOPPEMENT: 'DEVELOPPEMENT',
	BI: 'BI',
	EDITIQUE: 'EDITIQUE',
	INFRA: 'INFRA',
	CAFETERIA: 'CAFETERIA',
	ESPACE_PARTENAIRE: 'ESPACE PARTENAIRE',
	DSN: 'DSN',
})

export const FORM_DEFAULT = Object.freeze({
	PROJECT: {
		id: null,
		title: '',
		description: '',
		status: STATUS.WAITING,
		date_start: '',
		date_end: '',
		progression: 0,
		service: 'DIRECTION',
		applicant: '',
		referent_info: '',
		referent_business: '',
		users: ['DIRECTION', 'DSI'],
		priority: false,
		clickup: '',
		link: '',
		fields: [],
		developers: [],
		timeSpent: 0.0,
		estimation: '',
	},
})

export const POPUP_VARIANTS = Object.freeze({
	INFO: 'INFO',
	WARNING: 'WARNING',
	DANGER: 'DANGER',
})

export const POPUP_ICONS = Object.freeze({
	INFO: 'info',
	WARNING: 'interrogation',
	DANGER: 'exclamation',
})

export const EVENT_SOURCE_MESSAGE_TYPES = Object.freeze({
	NEW_PROJECT: 'NEW_PROJECT',
	UPDATE_PROJECT: 'UPDATE_PROJECT',
	DELETE_PROJECT: 'DELETE_PROJECT',
	NEW_EVENT: 'NEW_EVENT',
	UPDATE_EVENT: 'UPDATE_EVENT',
	DELETE_EVENT: 'DELETE_EVENT',
	NEW_FILE: 'NEW_FILE',
	DELETE_FILE: 'DELETE_FILE',
})

export const TIMELINE_STATUS_COLOR = Object.freeze({
	[STATUS.PRODUCTION]: '#00ffbf',
	[STATUS.RECIPE]: '#ff8000',
	[STATUS.PROGRESS]: '#4c60fa',
	[STATUS.WAITING]: '#c999ff',
})
